<a href="https://colab.research.google.com/github/stefkong1982/netology.ru/blob/Master/%D0%BA%D1%812.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [63]:
import pandas as pd
from openpyxl import load_workbook

def parse_ks2(file_path):
    # Загружаем файл
    wb = load_workbook(file_path)
    ws = wb['КС-2 ИТОГО']

    # Определяем стартовую строку (после заголовков)
    start_row = 25
    data = []

    # Проходим по всем строкам листа
    for row_num, row in enumerate(ws.iter_rows(min_row=start_row, values_only=True), start=start_row):
        # Получаем значения из столбцов C-N (индексы 2-13)
        row_data = list(row[2:14])

        # Проверяем, есть ли данные в строке
        if any(cell is not None and cell != '' for cell in row_data):
            # Добавляем номер строки для отслеживания
            row_data.append(row_num)
            data.append(row_data)

    # Создаем DataFrame с правильными названиями столбцов
    columns = [
        'п/п',                              # Столбец C (индекс 2)
        'Подпозиция',                       # Столбец D (индекс 3) - безымянный столбец
        'поз. по сме-те',                   # Столбец E (индекс 4)
        'Шифр расценки и коды ресурсов',    # Столбец F (индекс 5)
        'Наименование работ и затрат',      # Столбец G (индекс 6)
        'Единица измерения',                # Столбец H (индекс 7)
        'Кол-во единиц',                    # Столбец I (индекс 8)
        'Цена на единицу измерения, руб.',  # Столбец J (индекс 9)
        'Попра-вочные коэфф., нормы НР и СП', # Столбец K (индекс 10)
        'Всего затрат в базисном уровне цен, руб.', # Столбец L (индекс 11)
        'Индексы пересчета, нормы НР и СП', # Столбец M (индекс 12)
        'ВСЕГО затрат, руб.',               # Столбец N (индекс 13)
        'Номер строки в Excel'              # Дополнительный столбец для отладки
    ]

    df = pd.DataFrame(data, columns=columns)

    # Очищаем данные от служебных символов и лишних пробелов
    for col in df.columns:
        df[col] = df[col].apply(lambda x: x.strip() if isinstance(x, str) and x is not None else x)

    # Заменяем значения, которые могут быть формулами или ошибками
    df = df.replace({'=IF(D35="",0,2)': None, '=K23': None}, regex=True)

    return df

# Использование
df = parse_ks2('КС-2.xlsx')

In [64]:
df

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
0,None,ИТОГОВЫЙ AKT,None,None,None,None,None,None,None,None,None,None,25
1,None,О ПРИЕМКЕ ВЫПОЛНЕННЫХ РАБОТ,None,None,None,None,None,None,None,None,None,None,26
2,Номер,None,None,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",28
3,п/п,None,поз. по сме-те,None,None,None,None,None,None,None,None,None,29
4,1,None,2,3,4,5,6,7,8,9,10,11,30
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16551,None,None,None,None,None,None,None,None,None,"ВСЕГО ПО АКТУ формы КС-2, руб.:",=SUM(P35:P17717),None,17720
16552,Сдал,None,None,Генеральный директор \nОбщество с ограниченной...,None,None,None,None,None,Д.В. Петухов,None,None,17724
16553,None,None,None,None,None,"[должность,подпись(инициалы,фамилия)]",None,None,None,None,None,None,17725
16554,Принял,None,None,Генеральный директор \nОбщество с ограниченной...,None,None,None,None,None,А.А. Лебедева,None,None,17728
16555,None,None,None,None,None,"[должность,подпись(инициалы,фамилия)]",None,None,None,None,None,None,17729

In [65]:
# Удаляем строки с индексами от 0 до 7 включительно
df = df.iloc[8:]

In [66]:
df

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
8,1,1,1,09-08-001-03,Установка металлических столбов высотой до 4 м...,100 ШТ,0.79,None,None,None,,None,36
9,None,None,None,None,"Объем: 0,79=79/100",None,None,None,None,None,None,None,37
10,None,None,None,None,ЗП,None,None,375.75,,296.84,7.56,2244.13,38
11,None,None,None,None,ЭМ,None,None,732.4,,578.6,7.56,4374.19,39
12,None,None,None,None,в т.ч. ЗПМ,None,None,345.45,,272.91,7.56,2063.17,40
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16551,None,None,None,None,None,None,None,None,None,"ВСЕГО ПО АКТУ формы КС-2, руб.:",=SUM(P35:P17717),None,17720
16552,Сдал,None,None,Генеральный директор \nОбщество с ограниченной...,None,None,None,None,None,Д.В. Петухов,None,None,17724
16553,None,None,None,None,None,"[должность,подпись(инициалы,фамилия)]",None,None,None,None,None,None,17725
16554,Принял,None,None,Генеральный директор \nОбщество с ограниченной...,None,None,None,None,None,А.А. Лебедева,None,None,17728
16555,None,None,None,None,None,"[должность,подпись(инициалы,фамилия)]",None,None,None,None,None,None,17729

In [67]:
# Количество уникальных значений в колонке "Шифр расценки и коды ресурсов"
unique_codes_count = df["Шифр расценки и коды ресурсов"].nunique()
print(f"Уникальных значений в колонке 'Шифр расценки и коды ресурсов': {unique_codes_count}")

Уникальных значений в колонке 'Шифр расценки и коды ресурсов': 1939

In [68]:
# Сначала создадим копию DataFrame, чтобы избежать возможных ошибок
df_copy = df.copy()

# Далее заменяем пустые строки ('') на NA-значения
df_copy.loc[:, 'Шифр расценки и коды ресурсов'] = df_copy['Шифр расценки и коды ресурсов'].replace('', pd.NA)

# Теперь можем убрать строки с пустыми значениями
df_cleaned = df_copy.dropna(subset=['Шифр расценки и коды ресурсов'])

In [69]:
df_cleaned

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
8,1,1,1,09-08-001-03,Установка металлических столбов высотой до 4 м...,100 ШТ,0.79,None,None,None,,None,36
13,None,2,"1,1",23.3.08.02-0157,Трубы стальные прямоугольные (ГОСТ 8645-86) ра...,м,180,58.08,,10454.4,7.56,79035.26,41
14,None,3,"1,2",01.7.15.02-0051,Болты анкерные,т,0.0237,10068,,238.61,7.56,1803.9,42
19,2,4,2,м38-01-003-04,Изготовление прогонов ограждения забора из ста...,т,0.723,None,None,None,,None,47
24,None,5,"2,1",23.3.08.02-0064,Трубы стальные прямоугольные (ГОСТ 8645-86) ра...,м,498,13.29,,6618.42,7.56,50035.26,52
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16547,3514,184,10,Акт № 12 от 30.10.2020,"Генподрядные услуги по приемке работ, выполняе...",компл.,1,39666.39,None,39666.39,1,39666.39,17714
16548,3515,185,11,Акт № 12 от 30.10.2020,"Генподрядные услуги по сбору, проверке, выдаче...",компл.,1,66109.52,None,66109.52,1,66109.52,17715
16549,3516,186,12,Акт № 12 от 30.10.2020,Генподрядные услуги по контролю соблюдения тех...,компл.,1,2576.53,None,2576.53,1,2576.53,17716
16552,Сдал,None,None,Генеральный директор \nОбщество с ограниченной...,None,None,None,None,None,Д.В. Петухов,None,None,17724
16554,Принял,None,None,Генеральный директор \nОбщество с ограниченной...,None,None,None,None,None,А.А. Лебедева,None,None,17728

In [70]:
# Проверяем общее количество строк в очищенном DataFrame
total_rows_cleaned = len(df_cleaned)

# Проверяем количество пустых значений в колонке "ВСЕГО затрат, руб."
empty_total_cost_cleaned = df_cleaned['ВСЕГО затрат, руб.'].isnull().sum()

# Рассчитываем долю пустых значений
percentage_empty_cleaned = (empty_total_cost_cleaned / total_rows_cleaned) * 100

# Выводим результаты
print(f"Всего строк в очищенном DataFrame: {total_rows_cleaned}")
print(f"Пустых значений в колонке 'ВСЕГО затрат, руб.': {empty_total_cost_cleaned}")
print(f"Доля пустых значений (%): {percentage_empty_cleaned:.2f}%")

Всего строк в очищенном DataFrame: 3820
Пустых значений в колонке 'ВСЕГО затрат, руб.': 1443
Доля пустых значений (%): 37.77%

In [71]:
# Создаем полноценную копию очищенного DataFrame
df_final = df_cleaned.copy()

# Проверяем количество пустых значений в колонке "ВСЕГО затрат, руб."
empty_total_cost = df_final['ВСЕГО затрат, руб.'].isnull().sum()

# Удаляем строки с пустыми значениями в колонке "ВСЕГО затрат, руб."
df_final = df_final.dropna(subset=['ВСЕГО затрат, руб.'])

# Проверяем успешность удаления пустых значений
assert df_final['ВСЕГО затрат, руб.'].isnull().sum() == 0, \
    "В колонке 'ВСЕГО затрат, руб.' остались пустые значения!"

# Выводим размеры DataFrame до и после очистки
initial_size = len(df_cleaned)
final_size = len(df_final)
removed_rows = initial_size - final_size
remaining_percentage = (final_size / initial_size) * 100

# Выводим результаты
print(f"Текущий размер очищенного DataFrame: {initial_size} строк")
print(f"Удалено строк с пустыми значениями в колонке 'ВСЕГО затрат, руб.': {removed_rows}")
print(f"Итоговый размер DataFrame после очистки: {final_size} строк")
print(f"Доля оставшихся строк (%): {remaining_percentage:.2f}%")

Текущий размер очищенного DataFrame: 3820 строк
Удалено строк с пустыми значениями в колонке 'ВСЕГО затрат, руб.': 1443
Итоговый размер DataFrame после очистки: 2377 строк
Доля оставшихся строк (%): 62.23%

In [72]:
df_final

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
13,None,2,"1,1",23.3.08.02-0157,Трубы стальные прямоугольные (ГОСТ 8645-86) ра...,м,180,58.08,,10454.4,7.56,79035.26,41
14,None,3,"1,2",01.7.15.02-0051,Болты анкерные,т,0.0237,10068,,238.61,7.56,1803.9,42
24,None,5,"2,1",23.3.08.02-0064,Трубы стальные прямоугольные (ГОСТ 8645-86) ра...,м,498,13.29,,6618.42,7.56,50035.26,52
34,None,7,"3,2",07.2.07.13,Конструкции стальные,т,0.723,0,,0,7.56,0,62
45,None,9,"4,1",08.3.09.01-0008,"Профилированный лист оцинкованный Н60-845-0,55",т,1.523149,11817.6,,17999.97,7.56,136079.74,73
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16545,3512,182,8,Акт № 12 от 30.10.2020,Генподрядные услуги по сбору объемов работ на ...,компл.,1,52889.37,None,52889.37,1,52889.37,17712
16546,3513,183,9,Акт № 12 от 30.10.2020,"Генподрядные услуги по проверке, выдаче замеча...",компл.,1,39666.39,None,39666.39,1,39666.39,17713
16547,3514,184,10,Акт № 12 от 30.10.2020,"Генподрядные услуги по приемке работ, выполняе...",компл.,1,39666.39,None,39666.39,1,39666.39,17714
16548,3515,185,11,Акт № 12 от 30.10.2020,"Генподрядные услуги по сбору, проверке, выдаче...",компл.,1,66109.52,None,66109.52,1,66109.52,17715
16549,3516,186,12,Акт № 12 от 30.10.2020,Генподрядные услуги по контролю соблюдения тех...,компл.,1,2576.53,None,2576.53,1,2576.53,17716

In [110]:
# Регулярное выражение для нахождения строк с любыми буквами
pattern = r'[A-Za-zА-Яа-яЁё]'

# Оставляем только строки, содержащие буквы
df_final = df_final[
    df_final['Шифр расценки и коды ресурсов'].astype(str).str.contains(pattern)
]

In [112]:
# Подсчет количества уникальных значений в колонке "Шифр расценки и коды ресурсов"
unique_codes = df_final['Шифр расценки и коды ресурсов'].nunique()

# Получение списка уникальных значений
unique_code_list = df_final['Шифр расценки и коды ресурсов'].unique()

# Расчёт распределения значений
code_distribution = df_final['Шифр расценки и коды ресурсов'].value_counts(normalize=True) * 100

# Вывод результатов
print(f"Количество уникальных значений в колонке 'Шифр расценки и коды ресурсов': {unique_codes}\n")
print("Список уникальных значений:")
for code in unique_code_list:
    print(code)

Количество уникальных значений в колонке 'Шифр расценки и коды ресурсов': 1017

Список уникальных значений:
Счет-фактура № 675 от 3 сентября 2019г
Счет-фактура № 660 от 28.08.2019г
т01-01-01-016
т01-01-01-043
Акт № 1 от 10.03.2020
т01-01-01-039
Акт № 1 от 30.04.2020
Счет-фактура № ФМ9532 от 26 марта 2020 г.
Акт №02 от 29.05.2020
Акт № 3 от 29.05.2020
Ц.поставщ.
Ц.пост.
Сч.факт. № КА-1350 от 22.05.2020г
т01-01-01-003
т01-01-01-042
т01-01-01-014
т01-01-01-043методические рекомендации Минстроя России №519/ пр от 04 09 2019
Сч.факт.№ШД000272513/01от 10 июня 2020г
Сч.фактура № 850от 19.06.2020г
ССЦ-11.2.08.02-0010
ССЦ-01.6.01.10-0015
ССЦ-12.1.02.10-0095
ССЦ-01.2.01.02-0052
ССЦ-14.3.01.01-0001
ССЦ-01.7.06.09-0007
ФССЦ-19.1.01.03-0057
ФССЦ-19.1.01.03-0033
ФССЦ-19.1.01.03-0024
ФССЦ-19.1.01.03-0022
ФССЦ-19.1.01.03-0021
ФССЦ-19.1.01.03-0047
ФССЦ-19.1.01.03-0046
ФССЦ-19.1.01.03-0045
ФССЦ-19.1.01.03-0044
ФССЦ-19.1.01.03-0071
Сч.фак. №584 от18 июня 2020г
ФССЦ-19.3.01.01-0013
ФССЦ-19.3.01.01-0012
ФССЦ-19.3.01.01-0011
ФССЦ-19.1.01.05-0003
ФССЦ-19.1.01.05-0002
ФССЦ-12.2.04.06-0002
ФССЦ-19.1.01.11-0001
ФССЦ-19.1.01.03-0026
ФССЦ-19.1.01.03-0048
ФССЦ-19.1.01.03-0023
ФССЦ-19.1.01.03-0049
ФССЦ-19.1.01.01-0021
ФССЦ-19.1.01.06-0003
ФССЦ-19.1.01.09-0025
ФССЦ-19.1.01.08-0003
ФССЦ-19.1.01.08-0001
ФССЦ-19.1.01.01-0022
ФССЦ-19.2.03.02-0080
ФССЦ-23.2.02.02-0017
ФССЦ-23.2.02.02-0014
ФССЦ-12.2.07.04-0016
ФССЦ-12.2.07.04-0019
ФССЦ-01.3.02.11-0023
ФССЦ-08.1.02.17-0034
ФССЦ-01.7.15.02-0055
ФССЦ-23.2.02.02-0016
ФССЦ-23.2.02.02-0015
ФССЦ23.2.02.02-0014
ФССЦ-23.2.02.02-0013
ФССЦ-23.2.02.02-0012
ФССЦ-23.2.02.02-0011
ФССЦ-12.2.07.04-0018
ФССЦ-12.2.07.04-0017
ФССЦ-12.2.07.04-0015
ФССЦ-12.2.07.04-0014
ФССЦ-24.3.02.01-0002
ФССЦ-24.1.02.01-0003
ФССЦ-24.3.02.01-0003
ФССЦ-24.1.02.01-0004
ФССЦ-24.3.02.01-0004
ФССЦ-24.1.02.01-0005
ФССЦ-07.2.05.02-0076
Сч.факт.№848 от 18июня 2020г.
Сч.факт.№851 от 23июня 2020г.
ФССЦ-14.1.06.02-0028
ФССЦ-04.3.02.09-0102
Сч.факт.№50150от 24 июля 2020г
ФССЦ01.7.06.01-0043
ФССЦ06.2.01.02-0011
ФССЦ-04.3.02.09-0823
ФССЦ-14.1.06.02-0006
ФССЦ-14.4.03.15-0017
ФССЦ-14.4.01.09-0314
Сч.факт.№774от 29 июня 2020г
ФССЦ-23.5.02.02-0009
ФССЦ-23.8.04.06-0315
ФССЦ-18.1.09.11-0071
ФССЦ-23.8.03.11-0699
ФССЦ-63.4.01.01-0003
ФССЦ-14.5.05.02-0001
ФССЦ14.4.02.09-0302
ФССЦ-12.2.08.01-0101
Сч.факт.№ 262 от 29 мая 2020г.
ФССЦ23.5.02.02-0002
ФССЦ08.3.11.01-0072
ФССЦ08.3.11.01-0047
ФССЦ08.3.08.02-0022
ФССЦ-18.5.08.05-0031
Сч.фактура №АН-0008898 от20 июля 2020г
Сч.фактура №АН-0008450 от13 июля 2020г
Сч.фактура №ШД000270242/01 от 25июня 2020г
ФССЦ-18.1.06.04-0003
ФССЦ-18.1.09.06-0061
ФССЦ-19.1.02.01-0012
ФССЦ-24.3.05.16-0111
ФССЦ-24.3.05.16-0161
ФССЦ-24.3.05.16-0131
ФССЦ-24.3.05.16-0132
ФССЦ-24.3.05.16-0133
ФССЦ-24.3.05.16-0134
ФССЦ-24.3.05.15-0156
ФССЦ-24.3.05.15-0155
ФССЦ-24.3.05.15-0150
ФССЦ-24.3.05.15-0145
ФССЦ-24.3.05.15-0143
ФССЦ-24.3.05.15-0142
ФССЦ-24.3.05.15-0111
ФССЦ-24.3.05.17-0002
ФССЦ-24.3.05.17-0003
ФССЦ-24.3.05.17-0004
ФССЦ-12.2.07.04-0156
ФССЦ-12.2.07.04-0158
Сч.фактура №04073/20 от 28 июля 2020г
ФССЦ-24.3.05.16-0135
ФССЦ-24.3.05.15-0160
ФССЦ-24.3.05.07-0214
ФССЦ-23.8.04.14-0009
ФССЦ-04.3.01.09-0001
ФССЦ-23.5.02.02-0058
ФССЦ-23.8.04.06-0073
ФССЦ-23.8.04.08-0165
ФССЦ-14.4.01.01-0003
ФССЦ-14.4.02.09-0302
ФССЦ-12.2.08.01-0097
Сч.факт.№ 262 от 29 мая 2020г
ФССЦ-18.1.09.11-0069
ФССЦ-23.8.03.11-0697
ФССЦ-23.8.03.12-0011
ФССЦ-23.5.02.02-0002
ФССЦ-08.3.11.01-0072
ФССЦ-08.3.11.01-0047
ФССЦ-08.3.08.02-0022
Сч.фактура № 852от 19.06.2020г
ФССЦ-11.2.08.02-0010
ФССЦ-01.6.01.10-0015
ФССЦ01.7.06.09-0007
ФССЦ01.2.01.02-0054
ФССЦ01.2.01.02-0052
Сч.Фак.№ 103 от 23 июня 2020г
ФССЦ14.4.01.09-0314
ФССЦ14.4.03.15-0017
Сч.факт.№ 94 от 30.06.2020г
ФССЦ-01.2.01.02-0054
ФССЦ-01.2.01.02-0052
ФССЦ-04.3.02.09-0302
ФССЦ12.1.02.10-0095
ФССЦ-11.3.03.06-0002
Сч.факт.№637 от16.07.2020
Сч.факт.№ 451 от 22.07.2020
Сч.факт.№466 от 12.08.2020г
Сч.факт.№451 от 22.07.2020г
Сч.факт.№209 от 31.07.2020г.2020г
ФССЦ-20.5.02.07-0003
ФССЦ-20.2.05.04-0011
ФССЦ-24.3.01.06-0042
ФССЦ-23.8.03.02-0002
Сч.факт.№ 057/17508 от 03.08.2020г
Сч.факт.№ 057/17240 от 06.07.2020г
Сч.факт.№ 057/17241от 06.07.2020г
Сч.факт.№ 057/14934от 13.07.2020г
ФССЦ-23.3.06.06-0010
Сч.факт.№ 057/15751от 19.07.2020г
ФССЦ-21.1.06.10-0411
ФССЦ-21.1.06.10-0410
ФССЦ-21.1.06.10-0409
ФССЦ-21.1.06.10-0408
ФССЦ-21.1.06.10-0407
ФССЦ-21.1.06.10-0378
ФССЦ-21.1.06.10-0377
ФССЦ-21.1.06.10-0375
ФССЦ-21.1.06.10-0169
ФССЦ-21.1.06.10-0167
ФССЦ-21.1.06.10-0402
ФССЦ-21.1.06.10-0359
ФССЦ-21.1.06.10-0416
Сч.факт.№ 057/19414от 21.07.2020г
Сч.факт.№ 8894от 27.07.2020г
ФССЦ-20.2.09.04-0012
ФССЦ-20.2.09.04-0011
ФССЦ-20.2.09.04-0006
ФССЦ-20.2.10.03-0002
Сч.факт.№ 057/10750от 27.05.2020г
ФССЦ-08.3.08.02-0052
ФССЦпг01-01-01-043
ФССЦпг03-21-01-055
ФССЦ01.4.01.10-0016
ФССЦ01.4.01.03-0152
ФССЦ-08.3.10.02-0001
ФССЦ-23.5.02.02-0090
ФССЦ11.2.13.04-0012
ФССЦ-02.3.01.02-0015
ФССЦ02.3.01.02-0015
ФССЦ04.1.02.03-0010
ФССЦ01.2.01.01-0019
ФССЦ04.2.01.01-0036
ФССЦ04.2.01.01-0031
ФЕР16.2.02.07-0161
ФССЦ-23.3.03.02-0137
ФССЦ-23.8.04.06-0086
ФССЦ-23.3.03.02-0111
ФССЦ-23.8.04.06-0079
ФССЦ-23.5.02.02-0101
ФССЦ-23.5.02.02-0094
ФССЦ-14.2.01.01-0003
ФССЦ-14.4.02.02-0104
ФССЦ-12.2.08.01-0099
ФССЦ-05.2.02.01-0042
ФССЦ-02.2.05.04-0087
ФССЦ-05.1.01.09-0002
ФССЦ-05.1.01.09-0001
ФССЦ-08.1.02.06-0043
ФССЦ-07.2.05.01-0032
ФССЦ-08.3.05.02-0061
ФССЦ-08.4.03.03-0032
ФССЦ-23.4.01.03-0009
ФССЦ-23.8.04.06-0064
ФССЦ-04.1.02.01-0003
ФССЦ-08.4.03.03-0031
ФССЦ-08.4.03.03-0029
ФССЦ-08.4.03.03-0030
ФССЦ-04.1.02.01-0006
ФССЦ-04.1.02.01-0009
ФССЦ-05.1.01.13-0043
ФССЦ04.3.01.09-0014
ФССЦ12.1.02.01-0011
Сч.факт. №1416 от 09.июля 2020г
ФССЦ-23.4.01.03-0045
ФССЦ-23.8.02.01-0009
Сч.факт. №1416 от 09.июля 2020гайс-лист
ФССЦ-23.4.01.03-0043
ФССЦ-23.8.02.01-0008
ФССЦ-23.4.01.03-0008
ФССЦ-23.8.02.01-0006
ФССЦ-23.8.02.02-0015
ФСЦ-23.8.02.05-0015
Сч. факт № 437 от 23 мая 2020г.№481 от 06 июня 2020г.№575 от 02 июня 2010г
ФССЦ-23.3.06.02-0008
ФССЦ-23.8.04.06-0312
ФССЦ-23.7.01.01-0006
ФССЦ-65.1.04.03-0036
ФССЦ-18.2.08.05-0012
ФССЦ-12.2.07.04-0111
ФССЦ-19.2.03.02-0199
ФССЦ-19.2.03.02-0308
ФССЦ-19.2.03.01-0045
Сч.фак.№УТ2578 от 27.04.2020
ФССЦ-19.1.05.03-0003
ФССЦ-19.1.05.03-0002
ФССЦ-69.2.02.02-0003
ФССЦ-19.2.02.02-0028
ФССЦ-19.2.02.02-0027
ФССЦ-19.2.03.02-0175
ФССЦ-19.2.03.02-0307
ФССЦ19.2.03.01-0033
ФССЦ-19.3.01.06-0064
ФССЦ-19.1.05.03-0001
ФССЦ-19.2.03.02-0163
ФССЦ-19.2.03.01-0033
Сч.фак.№УТ4421 от 29.06.2020
ФССЦ-19.3.01.09-0002
ФССЦ-19.2.02.02-0011
Сч.фак.№УТ6051 от 12.08.2020
ФССЦ-19.3.01.09-0003
ФССЦ-19.2.03.02-0164
ФССЦ-19.2.03.02-0087
ФССЦ-19.3.01.09-0001
ФССЦ-19.2.03.01-0172
Сч.фак.№021-00198679/3316 от 05.08. 2020г
ФССЦ-01.7.15.04-0041
ФССЦ-01.7.15.07-0004
Сч.фак.№ УТ5545 от 30.07. 2020г
Сч.фак.№021-010198679/3316 от 05.08. 2020г
Сч.факт № 20390 от 05.08.2020г
ФССЦ-21.2.03.08-0012
ФССЦ-21.2.03.05-0066
ФССЦ-24.3.03.02-0002
ФССЦ-24.3.05.08-0202
ФССЦ-24.3.05.15-0199
ФССЦ-24.3.05.15-0172
ФССЦ-24.3.05.02-0101
ФССЦ-24.3.05.07-0159
ФССЦ-24.3.05.17-0112
ФССЦ-24.1.02.01-0024
ФССЦ-24.3.03.02-0001
ФССЦ-01.7.19.02-0051
ФССЦ-24.3.05.08-0201
ФССЦ-24.3.05.15-0195
ФССЦ-24.3.05.12-0001
ФССЦ-24.3.05.07-0155
ФССЦ-24.3.05.10-0001
ФССЦ-24.3.05.05-0001
ФССЦ-24.3.05.17-0111
ФССЦ-23.3.03.02-0102
ФССЦ-23.3.03.02-0047
ФССЦ-18.2.06.10-0003
Сч.факт. №6038 от 01 июня 2020г
ФССЦ-12.2.04.11-0008
ФССЦ-07.2.06.04-0043
Сч. факт. № 83 от 03.08.2020
Сч. факт. № 89 от 06.08.2020
ФССЦ-01.7.15.07-0035
ФССЦ-01.7.15.14-0061
ФССЦ-14.5.02.02-0105
ФССЦ-01.7.19.03-0001
Сч. факт. № 80 от 30.07.2020
Сч. факт. №98 от 24.08.2020
Сч. факт. №96 от 24.08.2020
ФССЦ-18.5.02.03-0011
Сч. факт. №80 от 30.07.2020
Сч. факт. №83от 03.08.2020
Сч. факт. №89от 06.08.2020
ФССЦ-01.7.15.07-0014
Сч. факт. №82от 03.08.2020
Сч. факт. №96от 24.08.2020
Сч. факт. №92от 17.08.2020
ФССЦ24.3.05.07-0139
ФССЦ-24.3.02.01-0017
ФССЦ-24.1.02.01-0113
ФССЦ-24.3.05.15-0164
ФССЦ-24.3.05.15-0163
ФССЦ-24.3.05.15-0161
ФССЦ-24.3.05.07-0144
ФССЦ-24.3.05.07-0156
ФССЦ-24.3.05.07-0074
ФССЦ-24.3.02.01-0016
ФССЦ-24.3.05.15-0159
ФССЦ-18.1.09.07-0025
ФССЦ-24.3.02.01-0015
ФССЦ-24.3.05.15-0153
ФССЦ-24.3.05.07-0140
ФССЦ-24.3.05.07-0134
ФССЦ-24.3.05.07-0154
ФССЦ-24.3.05.07-0112
ФССЦ-18.1.09.07-0024
ФССЦ-24.3.02.01-0014
ФССЦ-24.3.05.07-0153
ФССЦ-24.3.05.07-0120
ФССЦ-24.3.02.01-0013
ФССЦ-24.3.05.07-0131
ФССЦ-24.3.05.07-0152
ФССЦ-18.1.09.07-0022
ФССЦ-24.3.02.01-0012
ФССЦ-18.1.09.07-0021
ФССЦ-24.3.05.16-0210
ФССЦ-24.3.05.16-0208
ФССЦ-24.3.05.15-0191
ФССЦ-24.3.05.07-0062
ФССЦ-24.3.05.07-0151
ФССЦ-18.1.09.08-0223
ФССЦ-12.2.07.05-0117
ФССЦ-23.3.03.02-0030
ФССЦ-23.7.01.03-0004
ФССЦ-23.8.01.19-0023
ФССЦ-23.8.01.19-0002
ФССЦ-23.8.03.07-0112
ФССЦ-23.8.03.07-0111
ФССЦ-18.1.05.03-0013
ФССЦ-18.1.05.03-0012
ФСЦ-24.3.05.15-0164
ФССЦ-23.1.02.06-0037
ФССЦ23.1.02.06-0035
ФССЦ24.3.02.01-0015
ФССЦ-18.1.09.08-0224
ФССЦ-12.2.07.05-0113
ФССЦ-19.1.02.01-0002
Сч.факт.№5312 от 17 июля 2020г.
ФССЦ-65.1.04.03-0035
ФССЦ18.2.08.09-0004
ФССЦ-23.3.06.05-0004
ФССЦ-23.8.04.08-0161
ФССЦ-23.8.04.14-0007
ФССЦ-23.3.06.05-0001
ФССЦ-63.4.01.01-0002
ФССЦ-23.8.03.03-0214
ФССЦ-18.1.06.04-0011
ФССЦ-69.1.02.01-0011
ФССЦ-23.8.03.11-0677
ФССЦ-23.3.06.05-0006
ФССЦ-23.8.04.06-0063
ФССЦ-23.8.04.12-0211
ФССЦ-07.2.07.12-0031
ФССЦ-18.1.09.06-0026
Сч. факт. №4910от 01.06.2020
ФССЦ-18.2.08.09-0056
ФССЦ-23.8.03.05-0006
ФССЦ-23.8.03.11-0675
ФССЦ-18.1.09.06-0025
ФССЦ-18.2.08.09-0055
ФССЦ-23.3.06.05-0005
ФССЦ-23.8.03.05-0005
ФССЦ-23.8.03.11-0672
ФСЦ-24.3.05.07-0122
ФССЦ-07.2.06.03-0127
ФССЦ-07.2.06.03-0189
Сч.фактура № 850от 19.06.2020ги Сч.факт. № 1140 от 05.08.2020
Сч.факт.№ ШД000270242/01 от 25 июня 2020г.
ФССЦ18.2.08.09-0086
ФССЦ18.2.08.09-0085
ФССЦ-18.1.09.11-0103
ФССЦ18.1.09.11-0110
ФЕР18.1.09.07-0209
ФССЦ18.1.09.07-0208
ФССЦ18.1.09.07-0207
ФССЦ18.1.09.07-0206
ФССЦ63.4.05.01-0004
ФССЦ-19.1.02.01-0011
ФССЦ23.8.03.11-0682
ФССЦ23.8.03.11-0680
ФССЦ23.8.03.11-0677
ФССЦ23.8.03.11-0673
ФССЦ23.8.03.11-0679
ФССЦ-23.8.03.11-0676
ФССЦ23.7.01.05-0005
ФСЦЦ23.7.01.05-0004
ФССЦ23.7.01.05-0003
ФССЦ23.3.06.05-0004
ФССЦ23.3.06.05-0003
ФССЦ23.3.06.05-0002
ФССЦ23.3.06.05-0001
ФССЦ23.3.06.02-0008
ФССЦ23.3.06.02-0007
ФССЦ23.3.06.02-0006
ФССЦ23.3.06.02-0005
ФССЦ23.3.06.02-0003
ФССЦ23.3.06.02-0002
ФССЦ23.3.06.02-0001
ФССЦ-23.8.04.06-0087
ФССЦ-23.8.04.06-0075
ФССЦ23.8.04.06-0064
ФССЦ-23.8.04.06-0062
ФССЦ-23.8.04.08-0089
ФССЦ23.8.04.08-0057
ФССЦ-23.8.04.08-0054
ФССЦ23.8.04.08-0062
ФССЦ23.8.04.08-0056
ФССЦ-23.8.04.08-0051
ФССЦ-12.2.08.01-0044
ФССЦ-12.2.08.01-0040
ФССЦ12.2.08.01-0034
ФССЦ-12.2.08.01-0031
ФССЦ-12.2.08.01-0028
ФССЦ-12.2.08.01-0025
ФССЦ-12.2.08.01-0023
ФССЦ-12.2.08.01-0022
ФССЦ-12.2.08.01-0021
ФССЦ-12.2.04.03-0033
ФССЦ-23.1.03.02-0011
ФССЦ-23.1.03.02-0009
ФССЦ23.1.03.02-0006
ФССЦ23.1.03.02-0005
ФССЦ-23.1.03.02-0004
ФССЦ01.7.15.12-0013
ФССЦ01.7.15.03-0032
ФССЦ06.2.05.03-0005
ФССЦ06.2.05.05-0019
Сч.факт.№ Л117963 от 17.07.2020г.2020г
Сч.факт.№ 057/15750 от 19.07.2020г
ФССЦ-62.1.02.22-0011
ФССЦ-21.2.03.05-0070
ФССЦ-21.2.03.05-0073
Сч.факт.№ Л1179664от 17.07.2020г
Сч.факт.№ 057/14933от 13.07.2020г
Сч.фак.№1140от 05.08.2020г.и №850от19.06.2020г
Сч.фак.№1140от 05.08.2020г.и №850 от19.06.2020г
Сч.фак. №1140от 05.08.2020г.и  №850 от19.06.2020г
ФССЦ-12.1.02.10-0095
ФССЦ-14.3.01.01-0001
Сч.фактура № 103от 23 июня.2020г
Сч.фактура № 774 от 29 июня.2020г
Сч.фактура №153 от 10.08.2020г
ФССЦ04.1.02.05-0006
ФССЦ08.1.02.17-0097
Сч.фактура №810от 05.08.2020г
Сч.фактура № 641от 20.07.2020г
ФССЦ01.2.01.02-0001
ФССЦ04.2.01.01-0041
ФССЦ01.7.12.11-0162
ФССЦ04.2.01.01-0037
ФССЦ04.1.02.03-0006
ФССЦ4.3.02.13-0004
ФССЦ05.2.02.11-0018
ФССЦ01.7.12.05-0161
ФССЦ04.1.02.03-0003
ФССЦ04.2.01.01-0039
ФССЦ05.2.03.03-0032
ФССЦ05.2.03.03-0031
Сч.фак.№33 от 7сентября 2020г
ФССЦ16.2.01.02-0002
ФССЦ16.2.02.07-0131
ФССЦ16.2.02.07-0121
ФССЦ16.2.02.02-0153
ФССЦ16.2.02.02-0132
ФССЦ16.2.02.03-0001
ФССЦ16.2.02.04-0291
ФССЦ16.2.02.04-0081
ФССЦ16.2.02.04-0032
ФССЦ16.2.02.10-0021
ФССЦ02.2.05.01-0011
ФССЦ16.3.02.02-0002
ФССЦпг03-21-01-020
ФССЦ11.1.03.06-0087
ФССЦ08.3.05.02-0056
ФССЦ04.1.02.05-0011
ФССЦ08.4.03.03-0004
ФССЦ08.4.03.02-0001
Сч.фак.№648от10.08.2020г
ФССЦ02.2.05.04-0031
т03-21-01-020
ФССЦ01.7.15.03-0033
Сч.фак.№23от20.08.2020г
ФССЦ04.1.02.05-0003
ФССЦ11.2.02.01-0071
ФССЦ11.2.02.01-0073
ФССЦ11.2.02.01-0072
ФССЦ01.7.04.07-0022
ФССЦ11.2.14.02-0004
ФССЦ01.7.04.04-0001
ФССЦ01.7.04.04-0021
Сч.фак.№52от 05.08.2020
ФССЦ09.4.02.07-0013
ФССЦ09.4.02.07-0014
ФССЦ11.2.02.01-0052
ФССЦ01.7.04.07-0021
ФССЦ09.4.02.07-0015
ФССЦ09.4.03.05-0002
ФССЦ09.1.01.01-0021
ФССЦ01.7.04.01-0001
ФССЦ61.2.02.01-0019
ФССЦ61.2.02.03-0026
ФССЦ61.2.07.02-0050
ФССЦ61.2.07.02-0082
ФССЦ61.2.07.06-0005
ФССЦ61.2.02.02-0051
ФССЦ21.1.08.01-0132
ФССЦ21.1.08.01-0133
ФССЦ24.3.01.02-0012
ФССЦ23.8.03.02-0002
ФССЦ20.2.05.04-0028
ФССЦ20.5.02.06-0030
ФССЦ14.2.02.12-0801
ФССЦ61.1.03.03-0003
Сч.фак.№ 50820004 от 05.08.2020
Сч.фак.№ 17/30-07от 30.07.2020г.
Сч.фак.№19652от 16.07.2020г.
ФССЦ20.2.05.04-0002
ФССЦ20.2.05.07-0002
ФССЦ20.2.05.09-0020
ФССЦ20.2.05.09-0069
ФССЦ20.2.05.09-0040
ФССЦ24.3.03.05-0012
ФССЦ24.3.03.13-0305
Сч.фак.№ДП-55167от 03.09.2020г.
Сч.фак.№ДП-55167 от 03.09.2020г.
Сч.фак.№СчфЛ-0000013728от 11.09.2020г.
ФССЦ20.2.06.05-0013
Сч.фак.№ 238от 14.08.2020г.
Сч.фак.№ 19652от 16.07.2020г.
ФССЦ20.2.02.04-0013
Сч.фак.№ 20119от 21.07.2020г.
ФССЦ24.3.03.05-0013
Сч.фак.№СфЛ143632от 19.08.2020г.
Сч.фак.№СфЛ143635от 19.08.2020г.
Сч.фак.№СфЛ117966от 17.07.2020г.
ФССЦ01.7.04.01-0002
ФССЦ21.1.06.09-0151
ФССЦ21.1.08.01-0154
ФССЦ23.8.03.02-0003
Сч.фак.№СфЛ117964от 17.07.2020г.
Сч.фак.№СфЛ128878от 31.07.2020г.
Сч.фак.№СфЛ120608от 22.07.2020г.
ФССЦ21.1.04.01-0004
ФССЦ24.3.01.02-0001
ФССЦ-01.7.15.10-0017
ФССЦ20.2.09.05-0003
ФССЦ20.2.09.05-0001
Сч.фак.№ 186246от 19.08.2020г.
Сч.фак.№ СфЛ143632 от 19.08.2020
Сч.фак.№ СфЛ0000013728 от 11.09.2020
ФССЦ04.1.02.01-0006
Сч.фак.№ 239 от 14.08.2020
ФССЦ21.1.08.01-0151
Сч.фак.№ 370 от 02.09.2020
Сч.фак.№254от 02.07.2020г.
Сч.фак.№Е-00189353/8050от 17.08.2020г.
Сч.фак.№СчфЛ-0000013730от 13.09.2020г.
Сч.фак.№829от 16.09.2020г.
Сч.факт. № 1000от 30 октября 2020г
Сч.фак.№СфЛ143631 от 18.08.2020г.
ФССЦ20.5.02.04-0001
ФССЦ27.1.01.01-0013
Сч.фак.№1752 от 02.09.2020
ФССЦ-21.2.03.05-0042
ФССЦ-21.2.03.05-0045
ФССЦ-21.2.03.05-0047
ФССЦ-21.2.03.05-0051
ФССЦ-62.1.02.22-0032
ФССЦ-62.1.02.22-0131
ФССЦ-20.4.02.01-0019
Сч.фак.№057/22089 от 11.09.2020
ФССЦ-20.5.02.04-0008
ФССЦ-27.1.01.01-0011
Сч.фак.№057/22610 от 16.09.2020
ФССЦ-20.3.01.02-0002
ФССЦ-08.1.02.13-0005
ФССЦ-08.3.07.01-0041
ФССЦ-25.2.01.01-0018
ФССЦ-21.2.03.05-0049
Сч.фак.№323 от 24.09.2020
ФССЦ-07.5.01.02-0031
Сч.факт. № 1752 от 02.09.2020
Сч.факт. № ШД 00280975/01 от 03.09.2020
Сч.факт. № 057/22089 от 11.09.2020
ФССЦ20.1.02.23-0211
Сч.факт. № 25274 от 21.09.2020г
Т.н. №19 от 30.10.2020гУниф.форма № Торг-12
Сч.фак.№20-00136от30.10.2020
Акт №18 от 30.10.2020
ФССЦ07.2.07.04-0011
ФССЦ07.2.07.12-0031
Сч.фак.№ К-9105 от 10 сентября 2020
ФССЦ04.1.02.05-0026
ФССЦ07.2.07.04-0014
ФССЦ07.2.07.04-0001
ФССЦ07.2.07.04-0003
ФССЦ 07.2.07.12-0034прилож. 9.1 сталь марки С345
ФССЦ 07.2.07.12-0034
ФССЦ23.3.08.01-0114
ФССЦ23.3.08.01-0121
ФССЦ08.3.09.04-0035
ФССЦ07.1.03.05-0011
ФССЦ07.2.07.12-0011
ФССЦ01.7.15.01-0001
ФССЦ23.3.08.01-0123
УПД № 273 от 30.09.2020
УПД №85 от 05.08.2020
УПД № 5686 от 13.08.2020, № УТ-1635 от 29.07.2020
УПД № УТ-1635 от 29.07.2020
УПД № 10416039 от 10.08.2020
УПД № 5170 от 27.07.2020, №5686 от 13.08.2020
УПД № 10209133 от 27.07.2020
СФ №Е-00189360/8050 от 25.08.2020
УПД № 1144 от 04.08.2020
УПД № 1356 от 27.07.2020
УПД № 85,86 от 05.08.2020
СФ № УП-191 от 01.09.2020
Торг-12 № 3275 от 16.07.2020
УПД № 19798 от 19.08.2020
УПД № 244802 от 19.08.2020
УПД № 95 от 29.07.2020
Торг-12 № РнП0001113 от 02.09.2020
УПД № 06636 от 03.09.2020
СФ № 0828-0000003 от 28.08.2020
Торг-12 № 23265 от 02.09.2020
УПД № 97 от 24.08.2020
УПД № 223 от 09.09.2020
Торг-12 №112 от 28.07.2020
УПД № 1938 от 22.07.2020
УПД № 8057 от 18.08.2020
УПД № 004/2020-0037571 от 28.07.2020
УПД № СО000130208 от 12.08.2020
СФ № 464 от 04.08.2020
Торг-12 № 1979 от 02.09.2020
УПД № дпВК0013468от 07.09.2020
Акт №20 от 30.10.2020
Сч.фак.№ 275 от08.09.2020г
Сч.фак.№ 814-019от14.08..2020г
ФССЦ-14.3.02.01-0326
ФССЦ11.2.09.02-0003
ФССЦ1.2.09.05-0022
ФССЦ-14.5.09.07-0031
ФССЦ-14.4.03.17-0004
ФССЦ11.2.11.06-0003
ФССЦ23.3.08.02-0129
ФССЦ01.7.15.07-0131
ФССЦ12.2.05.06-0023
Сч.фак.№1142от 02.10..2020г
Сч.фак.№1258от 23.10..2020г
ФССЦ07.2.06.03-0195
ФССЦ07.2.06.04-0073
ФССЦ-08.3.09.04-0011
ФССЦ12.2.05.10-0004
ФССЦ23.3.08.02-0268
ФССЦ-11.1.03.06-0037
ФССЦ-14.2.02.11-0007
УПД № 10567944 от 19.08.2020
СФ № 1014-0000003 от 14.10.2020
СФ № 1016-0000002 от 16.10.2020
УПД № IPSI20-0082934/344 от 17.08.2020
УПД № СИ00178471 от 21.08.2020
УПД № 10566563 от 19.08.2020
УПД № 13678 от 24.08.2020
Торг-12 №142 от 02.09.2020
УПД № 5686 от 13.08.2020
Торг-12 № РнП0001112 от 02.09.2020
Торг-12 № РнП0001113,РнП0001112 от 02.09.2020
СФ №2089 от 30.09.2020
СФ № 2153 от 06.10.2020
СФ № 65 от 20.10.2020
СФ № 1793 от 27.08.2020
СФ № 1793 от 27.08.2020, № 1955 от 15.09.2020
СФ № 1793 от 27.08.202
СФ № 2088 от 30.09.2020
СФ № 1955 от 15.09.2020
СФ № 66 от 20.10.2020
СФ № 1793 от 27.08.2020, № 2088 от 30.09.2020
СФ №2088 от 30.09.2020
Акт №6 от 30.10.2020
ФССЦпг01-01-01-041
ФССЦ01.7.06.11-0003
ФССЦ01.7.17.12-0001
ФССЦ14.5.11.09-0103
ФССЦ14.5.11.09-0104
ФССЦ08.1.02.17-0091
ФССЦ04.3.01.09-0015
ФССЦ01.7.16.04-0011
Сч.фак. №23372 от 07.09.2020г
ФССЦ14.1.02.04-0103
ФССЦ01.6.03.01-0031
ФССЦ14.5.04.03-0104
ФССЦ11.2.04.05-0001
ФССЦ14.3.01.01-0001
ФССЦ11.3.03.06-0002
ФССЦ11.3.03.14-0034
ФССЦ11.3.03.14-0032
ФССЦ11.3.03.14-0022
ФССЦ11.3.03.14-0002
ФССЦ11.3.03.14-0012
ФССЦ06.2.05.03-0031
ФССЦ01.6.01.02-0006
ФССЦ01.6.01.02-0008
ФССЦ01.7.06.01-0042
ФССЦ07.2.06.03-0115
ФССЦ07.2.06.03-0199
ФССЦ12.2.04.02-0001
ФССЦ11.1.03.01-0003
ФССЦ11.2.11.04-0005
ФССЦ14.2.06.01-0108
ФССЦ14.4.01.02-0011
Сч.фак.№166 от 22.07.2020
ФССЦ14.5.11.10-0101
ФССЦ14.5.11.01-0003
ФССЦ14.5.11.06-0004
ФССЦ14.3.02.01-0005
ФССЦ14.5.11.02-0101
ФССЦ04.3.02.09-0823
ФССЦ14.1.06.02-0006
ФССЦ09.2.01.05-0091
ФССЦ01.6.04.02-0011
ФССЦ01.6.04.02-0006
ФССЦ07.2.07.13-0021
ФССЦ14.5.11.01-0001
ФССЦ07.1.01.01-0020
ФССЦ05.2.02.07-0010
ФССЦ01.7.04.01-0011
ФССЦ06.1.01.05-0017
ФССЦ04.3.02.13-0322
ФССЦ12.2.05.10-0019
ФССЦ14.5.01.01-0011
ФССЦ11.3.02.02-0010
ФССЦ11.3.03.01-0012
ФССЦ08.3.01.02-0027
ФССЦ08.3.05.02-0063
ФССЦ08.3.01.02-0028
ФССЦ08.3.01.02-0026
ФССЦ01.7.15.03-0001
ФССЦ08.3.08.01-0040
ФССЦ08.3.11.01-0062
ФССЦ08.3.05.02-0061
ФССЦ08.3.05.02-0073
ФССЦ8.3.08.02-0043
ФССЦ04.3.01.12-0111
ФССЦ04.3.01.09-0016
ФССЦ04.1.02.01-0003
ФССЦ04.1.02.05-0007
ФССЦ08.4.03.03-0003
ФССЦ08.4.03.03-0001
ФССЦ01.7.15.14-0101
ФССЦ08.3.09.01-0010
ФССЦ01.7.15.08-0011
ФССЦ04.1.02.01-0007
ФССЦ01.7.15.03-0041
ФССЦ08.3.01.02-0014
ФССЦ08.3.05.02-0062
ФССЦ05.1.07.28-0046
ФССЦ05.1.07.28-0074
ФССЦ05.1.07.28-0070
ФССЦ01.7.06.11-0011
ФССЦ11.1.03.01-0001
ФССЦ07.2.05.01-0032
ФССЦ04.3.01.12-0006
ФССЦ06.1.01.05-0015
ФССЦ08.3.11.01-0060
ФССЦ14.4.04.08-0003
ФССЦ64.1.03.03-0014
ФССЦ01.7.15.02-0051
ФССЦ19.1.05.04-0006
ФССЦ19.1.05.04-0007
ФССЦ69.2.02.05-0109
ФССЦ69.2.02.05-0108
ФССЦ19.1.01.11-0001
ФССЦ19.1.01.02-0001
ФССЦ19.3.01.01-0001
Сч.фак..№18125 от 16.07.2020
ФССЦ14.1.04.01-0001
Сч.фак..№18125от 16.07.2020
Сч.фак..№21-00198680/3316от5 августа 2020г
ФССЦ19.3.02.08-0022
ФССЦ23.2.02.02-0011
ФССЦ23.2.02.02-0012
ФССЦ01.7.15.04-0041
ФССЦ01.7.15.07-0004
ФССЦ24.3.02.01-0003
ФССЦ24.3.02.01-0004
ФССЦ12.2.07.04-0001
ФССЦ08.1.02.01-0011
Сч.фак..№ТС0000002142 от27 августа 2020г
ФССЦ18.1.10.06-0013
ФССЦ18.5.10.08-0002
ФССЦ18.1.10.07-0003
ФССЦ23.1.02.06-0003
ФССЦ18.5.13.01-0002
ФССЦ23.1.02.06-0006
ФССЦ18.5.13.01-0006
ФССЦ14.4.02.04-0101
ФССЦ18.2.06.08-0017
ФССЦ65.1.04.03-0033
ФССЦ18.2.08.08-0013
ФССЦ18.1.11.01-0002
ФССЦ18.1.09.08-0003
ФССЦ24.1.02.01-0115
ФССЦ24.3.02.01-0013
ФССЦ24.3.05.16-0132
ФССЦ24.3.05.15-0192
ФССЦ24.3.05.15-0143
ФССЦ24.1.02.01-0113
ФССЦ24.3.02.01-0012
ФССЦ18.1.09.08-0002
ФССЦ 18.1.09.11-0106
ФССЦ18.1.09.08-0012
ФССЦ23.8.01.01-0001
ФССЦ24.3.05.16-0131
ФССЦ24.3.05.07-0038
ФССЦ24.3.05.07-0040
ФССЦ24.3.02.01-0014
ФССЦ24.3.05.16-0133
ФССЦ24.3.05.15-0145
ФССЦ24.3.05.15-0148
ФССЦ24.3.05.07-0135
ФССЦ24.3.02.01-0005
ФССЦ24.3.05.15-0154
ФССЦ12.2.07.04-0190
ФССЦ12.2.07.04-0189
ФССЦ12.2.07.04-0187
ФССЦ12.2.07.04-0186
ФССЦ01.7.19.02-0052

In [105]:
# Подсчет количества уникальных значений в колонке "Единица измерения"
unique_units = df_final['Единица измерения'].nunique()

# Получение списка уникальных значений
unique_unit_list = df_final['Единица измерения'].unique()

# Расчёт распределения значений
unit_distribution = df_final['Единица измерения'].value_counts(normalize=True) * 100

# Вывод результатов
print(f"Количество уникальных значений в колонке 'Единица измерения': {unique_units}\n")

print("\nРаспределение значений (проценты):")
print(unit_distribution.round(2))

Количество уникальных значений в колонке 'Единица измерения': 37


Распределение значений (проценты):
Единица измерения
шт.          26.08
т            13.21
ШТ           11.70
м             9.97
м3            8.58
м2            5.81
компл.        5.43
10 ШТ         4.33
кг            2.02
10 шт.        1.94
1000 м        1.77
1 Т ГРУЗА     1.64
10 м          1.51
100 шт.       1.22
л             0.97
1000 м2       0.84
100 ШТ        0.63
1000 шт.      0.34
К-Т           0.21
100 м         0.21
км            0.21
м.п.          0.21
П.М           0.17
шт..          0.13
              0.13
услуга        0.08
шт            0.08
лист          0.08
1000М         0.08
упак          0.08
кг.           0.08
КОМПЛ         0.04
набор         0.04
1000 ШТ       0.04
10 м2         0.04
100 м2        0.04
сут.          0.04
Name: proportion, dtype: float64

In [113]:
# Регулярное выражение для точного поиска слова "акт"
pattern = r'\bакт\b'

# Фильтруем строки с указанным словом
df_akt = df_final[
    df_final['Шифр расценки и коды ресурсов'].str.contains(pattern, regex=True, case=False)
]

# Сохраняем результат в Excel
output_file_path = 'filtered_exact_acts.xlsx'
df_akt.to_excel(output_file_path, index=False)

print(f'Файл успешно сохранён: {output_file_path}')

Файл успешно сохранён: filtered_exact_acts.xlsx

In [114]:
df_akt

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
131,16,3,1,Акт № 1 от 10.03.2020,Подбор и изучение юридической и технической до...,компл.,1,311765,None,=J189*I189,1,=L189*M189,189
132,17,4,2,Акт № 1 от 10.03.2020,"Установление наличия, сбор и оценка состояния ...",компл.,1,388235,None,=J190*I190,1,=L190*M190,190
133,18,5,3,Акт № 1 от 10.03.2020,Получение сведений о наличии особо охраняемой ...,компл.,1,317647.0,None,=J191*I191,1,=L191*M191,191
134,19,6,4,Акт № 1 от 10.03.2020,Получение сведений о наличии древесины и ценны...,компл.,1,300000,None,=J192*I192,1,=L192*M192,192
135,20,7,5,Акт № 1 от 10.03.2020,Обозначение на местности вырубаемых деревьев: ...,компл.,1,294118,None,=J193*I193,1,=L193*M193,193
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16545,3512,182,8,Акт № 12 от 30.10.2020,Генподрядные услуги по сбору объемов работ на ...,компл.,1,52889.37,None,52889.37,1,52889.37,17712
16546,3513,183,9,Акт № 12 от 30.10.2020,"Генподрядные услуги по проверке, выдаче замеча...",компл.,1,39666.39,None,39666.39,1,39666.39,17713
16547,3514,184,10,Акт № 12 от 30.10.2020,"Генподрядные услуги по приемке работ, выполняе...",компл.,1,39666.39,None,39666.39,1,39666.39,17714
16548,3515,185,11,Акт № 12 от 30.10.2020,"Генподрядные услуги по сбору, проверке, выдаче...",компл.,1,66109.52,None,66109.52,1,66109.52,17715
16549,3516,186,12,Акт № 12 от 30.10.2020,Генподрядные услуги по контролю соблюдения тех...,компл.,1,2576.53,None,2576.53,1,2576.53,17716

In [125]:
# Оставляем только строки, НЕ содержащие слово "акт"
df_filtered_final = df_final[
    ~df_final['Шифр расценки и коды ресурсов'].str.contains(pattern, regex=True, case=False)
]

In [126]:
df_filtered_final

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
64,None,12,"6,1",Счет-фактура № 675 от 3 сентября 2019г,Модульное здание из 2-х блок- контейнеров разм...,шт.,1,34391.53,,34391.53,7.56,259999.97,96
65,None,13,"6,2",Счет-фактура № 660 от 28.08.2019г,Блок- контейнер (улучшенный) разм.5850х2400х2...,шт.,3,9589.95,,28769.85,7.56,217500.07,97
85,8,2,2,т01-01-01-016,Погрузочные работы при автомобильных перевозка...,1 Т ГРУЗА,2.75,10.45,,28.74,7.56,217.26,123
101,11,5,5,т01-01-01-043,Погрузочные работы при автомобильных перевозка...,1 Т ГРУЗА,696.57,3.28,,2284.75,7.56,17272.71,143
121,14,2,2,т01-01-01-043,Погрузочные работы при автомобильных перевозка...,1 Т ГРУЗА,607.17,3.28,,1991.52,7.56,15055.87,171
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16485,3471,=D17632+1,3,договорная,Пандус в бокс 230х1200х1800 мм. Металлокаркас ...,компл.,2,39683.336,None,=J17633*I17633,1,=L17633*M17633,17633
16504,3477,14,1,договорная,Сопровождение строительно-монтажных работ со с...,компл.,1,450000,None,450000,1,450000,17665
16505,3478,15,2,договорная,Разработка паспорта благоустройства,компл.,1,400000,None,400000,1,400000,17666
16506,3479,16,3,договорная,Внесение сведений в АИС «Реестр зеленых насажд...,компл.,1,250000,None,250000,1,250000,17667
16507,3480,17,4,договорная,Согласование паспорта благоустройства по факти...,компл.,1,600000,None,600000,1,600000,17668

In [138]:
# Регулярное выражение для удаления строк, начинающихся с "ФССЦ"
fss_pattern = r'^ФССЦ.*'
ss_pattern = r'^ССЦ.*'
fer_pattern = r'^ФЕР.*'
fer_pattern = r'^ФЕР.*'
t_pattern = r'^т01.*'
fs_pattern = r'^ФСЦ.*'

In [139]:
mask_fss = ~df_filtered_final['Шифр расценки и коды ресурсов'].str.contains(fss_pattern, regex=True, case=False)
mask_fer = ~df_filtered_final['Шифр расценки и коды ресурсов'].str.contains(fer_pattern, regex=True, case=False)
mask_ss = ~df_filtered_final['Шифр расценки и коды ресурсов'].str.contains(ss_pattern, regex=True, case=False)
mask_ss = ~df_filtered_final['Шифр расценки и коды ресурсов'].str.contains(t_pattern, regex=True, case=False)
mask_ss = ~df_filtered_final['Шифр расценки и коды ресурсов'].str.contains(fs_pattern, regex=True, case=False)


# Логическое "И": Все маски должны быть истинны
final_mask = mask_fss & mask_fer & mask_ss

df_filtered_final = df_filtered_final[final_mask]

In [140]:
df_filtered_final

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
64,None,12,"6,1",Счет-фактура № 675 от 3 сентября 2019г,Модульное здание из 2-х блок- контейнеров разм...,шт.,1,34391.53,,34391.53,7.56,259999.97,96
65,None,13,"6,2",Счет-фактура № 660 от 28.08.2019г,Блок- контейнер (улучшенный) разм.5850х2400х2...,шт.,3,9589.95,,28769.85,7.56,217500.07,97
959,None,49,"25,1",Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Грунтовка SigmaFast 278(расход 0,225л/м2 толщ....",л,26.9,78.43,,2109.77,7.68,16203.01,1090
972,None,53,"26,2",Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Эмаль SigmaDur 520(расход 0,105л/м2толщ.60мкр....",л,12.6,98.04,,1235.3,7.68,9487.13,1103
1125,None,88,"41,1",Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Грунтовка SigmaFast 278(расход 0,225л/м2 толщ....",л,4.4,78.43,,345.09,7.68,2650.31,1260
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16485,3471,=D17632+1,3,договорная,Пандус в бокс 230х1200х1800 мм. Металлокаркас ...,компл.,2,39683.336,None,=J17633*I17633,1,=L17633*M17633,17633
16504,3477,14,1,договорная,Сопровождение строительно-монтажных работ со с...,компл.,1,450000,None,450000,1,450000,17665
16505,3478,15,2,договорная,Разработка паспорта благоустройства,компл.,1,400000,None,400000,1,400000,17666
16506,3479,16,3,договорная,Внесение сведений в АИС «Реестр зеленых насажд...,компл.,1,250000,None,250000,1,250000,17667
16507,3480,17,4,договорная,Согласование паспорта благоустройства по факти...,компл.,1,600000,None,600000,1,600000,17668

In [141]:
# Подсчет количества уникальных значений в колонке "Шифр расценки и коды ресурсов"
unique_codes = df_filtered_final['Шифр расценки и коды ресурсов'].nunique()

# Получение списка уникальных значений
unique_code_list = df_filtered_final['Шифр расценки и коды ресурсов'].unique()

# Расчёт распределения значений
code_distribution = df_filtered_final['Шифр расценки и коды ресурсов'].value_counts(normalize=True) * 100

# Вывод результатов
print(f"Количество уникальных значений в колонке 'Шифр расценки и коды ресурсов': {unique_codes}\n")
print("Список уникальных значений:")
for code in unique_code_list:
    print(code)

Количество уникальных значений в колонке 'Шифр расценки и коды ресурсов': 196

Список уникальных значений:
Счет-фактура № 675 от 3 сентября 2019г
Счет-фактура № 660 от 28.08.2019г
Счет-фактура № ФМ9532 от 26 марта 2020 г.
Ц.поставщ.
Ц.пост.
Сч.факт. № КА-1350 от 22.05.2020г
Сч.факт.№ШД000272513/01от 10 июня 2020г
Сч.фактура № 850от 19.06.2020г
Сч.фак. №584 от18 июня 2020г
Сч.факт.№848 от 18июня 2020г.
Сч.факт.№851 от 23июня 2020г.
Сч.факт.№50150от 24 июля 2020г
Сч.факт.№774от 29 июня 2020г
Сч.факт.№ 262 от 29 мая 2020г.
Сч.фактура №АН-0008898 от20 июля 2020г
Сч.фактура №АН-0008450 от13 июля 2020г
Сч.фактура №ШД000270242/01 от 25июня 2020г
Сч.фактура №04073/20 от 28 июля 2020г
Сч.факт.№ 262 от 29 мая 2020г
Сч.фактура № 852от 19.06.2020г
Сч.Фак.№ 103 от 23 июня 2020г
Сч.факт.№ 94 от 30.06.2020г
Сч.факт.№637 от16.07.2020
Сч.факт.№ 451 от 22.07.2020
Сч.факт.№466 от 12.08.2020г
Сч.факт.№451 от 22.07.2020г
Сч.факт.№209 от 31.07.2020г.2020г
Сч.факт.№ 057/17508 от 03.08.2020г
Сч.факт.№ 057/17240 от 06.07.2020г
Сч.факт.№ 057/17241от 06.07.2020г
Сч.факт.№ 057/14934от 13.07.2020г
Сч.факт.№ 057/15751от 19.07.2020г
Сч.факт.№ 057/19414от 21.07.2020г
Сч.факт.№ 8894от 27.07.2020г
Сч.факт.№ 057/10750от 27.05.2020г
Сч.факт. №1416 от 09.июля 2020г
Сч.факт. №1416 от 09.июля 2020гайс-лист
Сч. факт № 437 от 23 мая 2020г.№481 от 06 июня 2020г.№575 от 02 июня 2010г
Сч.фак.№УТ2578 от 27.04.2020
Сч.фак.№УТ4421 от 29.06.2020
Сч.фак.№УТ6051 от 12.08.2020
Сч.фак.№021-00198679/3316 от 05.08. 2020г
Сч.фак.№ УТ5545 от 30.07. 2020г
Сч.фак.№021-010198679/3316 от 05.08. 2020г
Сч.факт № 20390 от 05.08.2020г
Сч.факт. №6038 от 01 июня 2020г
Сч. факт. № 83 от 03.08.2020
Сч. факт. № 89 от 06.08.2020
Сч. факт. № 80 от 30.07.2020
Сч. факт. №98 от 24.08.2020
Сч. факт. №96 от 24.08.2020
Сч. факт. №80 от 30.07.2020
Сч. факт. №83от 03.08.2020
Сч. факт. №89от 06.08.2020
Сч. факт. №82от 03.08.2020
Сч. факт. №96от 24.08.2020
Сч. факт. №92от 17.08.2020
Сч.факт.№5312 от 17 июля 2020г.
Сч. факт. №4910от 01.06.2020
Сч.фактура № 850от 19.06.2020ги Сч.факт. № 1140 от 05.08.2020
Сч.факт.№ ШД000270242/01 от 25 июня 2020г.
Сч.факт.№ Л117963 от 17.07.2020г.2020г
Сч.факт.№ 057/15750 от 19.07.2020г
Сч.факт.№ Л1179664от 17.07.2020г
Сч.факт.№ 057/14933от 13.07.2020г
Сч.фак.№1140от 05.08.2020г.и №850от19.06.2020г
Сч.фак.№1140от 05.08.2020г.и №850 от19.06.2020г
Сч.фак. №1140от 05.08.2020г.и  №850 от19.06.2020г
Сч.фактура № 103от 23 июня.2020г
Сч.фактура № 774 от 29 июня.2020г
Сч.фактура №153 от 10.08.2020г
Сч.фактура №810от 05.08.2020г
Сч.фактура № 641от 20.07.2020г
Сч.фак.№33 от 7сентября 2020г
Сч.фак.№648от10.08.2020г
т03-21-01-020
Сч.фак.№23от20.08.2020г
Сч.фак.№52от 05.08.2020
Сч.фак.№ 50820004 от 05.08.2020
Сч.фак.№ 17/30-07от 30.07.2020г.
Сч.фак.№19652от 16.07.2020г.
Сч.фак.№ДП-55167от 03.09.2020г.
Сч.фак.№ДП-55167 от 03.09.2020г.
Сч.фак.№СчфЛ-0000013728от 11.09.2020г.
Сч.фак.№ 238от 14.08.2020г.
Сч.фак.№ 19652от 16.07.2020г.
Сч.фак.№ 20119от 21.07.2020г.
Сч.фак.№СфЛ143632от 19.08.2020г.
Сч.фак.№СфЛ143635от 19.08.2020г.
Сч.фак.№СфЛ117966от 17.07.2020г.
Сч.фак.№СфЛ117964от 17.07.2020г.
Сч.фак.№СфЛ128878от 31.07.2020г.
Сч.фак.№СфЛ120608от 22.07.2020г.
Сч.фак.№ 186246от 19.08.2020г.
Сч.фак.№ СфЛ143632 от 19.08.2020
Сч.фак.№ СфЛ0000013728 от 11.09.2020
Сч.фак.№ 239 от 14.08.2020
Сч.фак.№ 370 от 02.09.2020
Сч.фак.№254от 02.07.2020г.
Сч.фак.№Е-00189353/8050от 17.08.2020г.
Сч.фак.№СчфЛ-0000013730от 13.09.2020г.
Сч.фак.№829от 16.09.2020г.
Сч.факт. № 1000от 30 октября 2020г
Сч.фак.№СфЛ143631 от 18.08.2020г.
Сч.фак.№1752 от 02.09.2020
Сч.фак.№057/22089 от 11.09.2020
Сч.фак.№057/22610 от 16.09.2020
Сч.фак.№323 от 24.09.2020
Сч.факт. № 1752 от 02.09.2020
Сч.факт. № ШД 00280975/01 от 03.09.2020
Сч.факт. № 057/22089 от 11.09.2020
Сч.факт. № 25274 от 21.09.2020г
Т.н. №19 от 30.10.2020гУниф.форма № Торг-12
Сч.фак.№20-00136от30.10.2020
Сч.фак.№ К-9105 от 10 сентября 2020
УПД № 273 от 30.09.2020
УПД №85 от 05.08.2020
УПД № 5686 от 13.08.2020, № УТ-1635 от 29.07.2020
УПД № УТ-1635 от 29.07.2020
УПД № 10416039 от 10.08.2020
УПД № 5170 от 27.07.2020, №5686 от 13.08.2020
УПД № 10209133 от 27.07.2020
СФ №Е-00189360/8050 от 25.08.2020
УПД № 1144 от 04.08.2020
УПД № 1356 от 27.07.2020
УПД № 85,86 от 05.08.2020
СФ № УП-191 от 01.09.2020
Торг-12 № 3275 от 16.07.2020
УПД № 19798 от 19.08.2020
УПД № 244802 от 19.08.2020
УПД № 95 от 29.07.2020
Торг-12 № РнП0001113 от 02.09.2020
УПД № 06636 от 03.09.2020
СФ № 0828-0000003 от 28.08.2020
Торг-12 № 23265 от 02.09.2020
УПД № 97 от 24.08.2020
УПД № 223 от 09.09.2020
Торг-12 №112 от 28.07.2020
УПД № 1938 от 22.07.2020
УПД № 8057 от 18.08.2020
УПД № 004/2020-0037571 от 28.07.2020
УПД № СО000130208 от 12.08.2020
СФ № 464 от 04.08.2020
Торг-12 № 1979 от 02.09.2020
УПД № дпВК0013468от 07.09.2020
Сч.фак.№ 275 от08.09.2020г
Сч.фак.№ 814-019от14.08..2020г
Сч.фак.№1142от 02.10..2020г
Сч.фак.№1258от 23.10..2020г
УПД № 10567944 от 19.08.2020
СФ № 1014-0000003 от 14.10.2020
СФ № 1016-0000002 от 16.10.2020
УПД № IPSI20-0082934/344 от 17.08.2020
УПД № СИ00178471 от 21.08.2020
УПД № 10566563 от 19.08.2020
УПД № 13678 от 24.08.2020
Торг-12 №142 от 02.09.2020
УПД № 5686 от 13.08.2020
Торг-12 № РнП0001112 от 02.09.2020
Торг-12 № РнП0001113,РнП0001112 от 02.09.2020
СФ №2089 от 30.09.2020
СФ № 2153 от 06.10.2020
СФ № 65 от 20.10.2020
СФ № 1793 от 27.08.2020
СФ № 1793 от 27.08.2020, № 1955 от 15.09.2020
СФ № 1793 от 27.08.202
СФ № 2088 от 30.09.2020
СФ № 1955 от 15.09.2020
СФ № 66 от 20.10.2020
СФ № 1793 от 27.08.2020, № 2088 от 30.09.2020
СФ №2088 от 30.09.2020
Сч.фак. №23372 от 07.09.2020г
Сч.фак.№166 от 22.07.2020
Сч.фак..№18125 от 16.07.2020
Сч.фак..№18125от 16.07.2020
Сч.фак..№21-00198680/3316от5 августа 2020г
Сч.фак..№ТС0000002142 от27 августа 2020г
Сч.фак.№152от03.09.2020
Сч.фак. № 537 от 28 сентября 2020г
Сч.фак..№23745 от18.08. 2020г
Сч.фак..№Л128879 от31июля 2020г
Сч.фак..№354 от24июля 2020г
Сч.фак..№Л143633от19 августа. 2020г
Сч.фак. №СфЛ143700 от21 августа 2020г
Сч.фак.№6719 от 17 сентября 2020г
Сч.фак. № ШД000285353/01 от 30 сентября 2020г
Сч.фак. № ШД000285353/01 от 30 сентября 2020г.Сч.фак. № ШД000285355/01 от 30 сентября 2020г
Сч.факт.№177 от 25 июля 2020г.
Сч.факт.№УТД000026842 от 19 августа 2020г.
Cч.фак. № НЖ2-012243/ 8088 от 24.12.2020
Cч.фак.№ 80 от 24.12.2020
Тн 69 от 26.03.20
ТН 107 от 29.05.20
ТН 203 от 24.08.20
договорная
Сч/ф. № 253-001 от 09.09.2020

In [142]:
def filter_by_codes(input_codes):
    """
    Фильтрует df_filtered_final по заданным шифрам расценок и выводит сокращённый результат

    Parameters:
    input_codes (str или list): Шифр(ы) расценок для поиска
    """
    # Преобразуем вход в список, если передан одиночный код
    if isinstance(input_codes, str):
        input_codes = [input_codes]

    # Определяем интересующие нас столбцы
    columns_to_show = [
        'Шифр расценки и коды ресурсов',
        'Наименование работ и затрат',
        'Единица измерения',
        'Кол-во единиц',
        'Цена на единицу измерения, руб.'
    ]

    # Фильтруем DataFrame и выводим выбранные столбцы
    filtered_result = df_filtered_final[
        df_filtered_final['Шифр расценки и коды ресурсов'].isin(input_codes)
    ][columns_to_show]


    return filtered_result

# Пример использования:
# filter_by_codes("Акт № 1 от 10.03.2020")

In [152]:
filter_by_codes(["Счет-фактура № 675 от 3 сентября 2019г", 'Счет-фактура № ФМ9532 от 26 марта 2020 г.', 'Сч.факт. № КА-1350 от 22.05.2020г'])

,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб."
64,Счет-фактура № 675 от 3 сентября 2019г,Модульное здание из 2-х блок- контейнеров разм...,шт.,1,34391.53
959,Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Грунтовка SigmaFast 278(расход 0,225л/м2 толщ....",л,26.9,78.43
972,Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Эмаль SigmaDur 520(расход 0,105л/м2толщ.60мкр....",л,12.6,98.04
1125,Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Грунтовка SigmaFast 278(расход 0,225л/м2 толщ....",л,4.4,78.43
1138,Счет-фактура № ФМ9532 от 26 марта 2020 г.,"Эмаль SigmaDur 520(расход 0,105л/м2толщ.60мкр....",л,2.1,98.04
1516,Сч.факт. № КА-1350 от 22.05.2020г,"Гетекстиль Нетканный ""Геофлакс"" 200 2*1000м Це...",м2,2155,3.03

In [149]:
# Список значений для удаления
values_to_remove = ["Ц.поставщ.", "Ц.пост.", 'Счет-фактура № ФМ9532 от 26 марта 2020 г.', 'Сч.факт. № КА-1350 от 22.05.2020г']

# Фильтруем DataFrame, оставляя только строки, не входящие в список значений
filtered_df = df_filtered_final[
    ~df_filtered_final['Шифр расценки и коды ресурсов'].isin(values_to_remove)
]

In [150]:
filtered_df

,п/п,Подпозиция,поз. по сме-те,Шифр расценки и коды ресурсов,Наименование работ и затрат,Единица измерения,Кол-во единиц,"Цена на единицу измерения, руб.","Попра-вочные коэфф., нормы НР и СП","Всего затрат в базисном уровне цен, руб.","Индексы пересчета, нормы НР и СП","ВСЕГО затрат, руб.",Номер строки в Excel
64,None,12,"6,1",Счет-фактура № 675 от 3 сентября 2019г,Модульное здание из 2-х блок- контейнеров разм...,шт.,1,34391.53,,34391.53,7.56,259999.97,96
65,None,13,"6,2",Счет-фактура № 660 от 28.08.2019г,Блок- контейнер (улучшенный) разм.5850х2400х2...,шт.,3,9589.95,,28769.85,7.56,217500.07,97
2632,None,61,"38,2",Сч.факт.№ШД000272513/01от 10 июня 2020г,"Труба 400 ЧШГ с ЦПП Ц.54256/6/1,2/7,73",м,40,974.85,,38994,7.68,299473.92,2874
2652,None,65,"40,1",Сч.факт.№ШД000272513/01от 10 июня 2020г,"Манжета Ц.780/1,2/7,73",шт.,11,84.09,,924.99,7.68,7103.92,2894
2710,334,2,4,Сч.фактура № 850от 19.06.2020г,HPL-Лемарк светло-серый -SH 3050х1300х8 FR) (...,л,184,1863.28,,342843.52,7.68,2633038.23,2961
...,...,...,...,...,...,...,...,...,...,...,...,...,...
16485,3471,=D17632+1,3,договорная,Пандус в бокс 230х1200х1800 мм. Металлокаркас ...,компл.,2,39683.336,None,=J17633*I17633,1,=L17633*M17633,17633
16504,3477,14,1,договорная,Сопровождение строительно-монтажных работ со с...,компл.,1,450000,None,450000,1,450000,17665
16505,3478,15,2,договорная,Разработка паспорта благоустройства,компл.,1,400000,None,400000,1,400000,17666
16506,3479,16,3,договорная,Внесение сведений в АИС «Реестр зеленых насажд...,компл.,1,250000,None,250000,1,250000,17667
16507,3480,17,4,договорная,Согласование паспорта благоустройства по факти...,компл.,1,600000,None,600000,1,600000,17668

In [151]:
# Подсчет количества уникальных значений в колонке "Шифр расценки и коды ресурсов"
unique_codes = filtered_df['Шифр расценки и коды ресурсов'].nunique()

# Получение списка уникальных значений
unique_code_list = filtered_df['Шифр расценки и коды ресурсов'].unique()

# Расчёт распределения значений
code_distribution = filtered_df['Шифр расценки и коды ресурсов'].value_counts(normalize=True) * 100

# Вывод результатов
print(f"Количество уникальных значений в колонке 'Шифр расценки и коды ресурсов': {unique_codes}\n")
print("Список уникальных значений:")
for code in unique_code_list:
    print(code)

Количество уникальных значений в колонке 'Шифр расценки и коды ресурсов': 192

Список уникальных значений:
Счет-фактура № 675 от 3 сентября 2019г
Счет-фактура № 660 от 28.08.2019г
Сч.факт.№ШД000272513/01от 10 июня 2020г
Сч.фактура № 850от 19.06.2020г
Сч.фак. №584 от18 июня 2020г
Сч.факт.№848 от 18июня 2020г.
Сч.факт.№851 от 23июня 2020г.
Сч.факт.№50150от 24 июля 2020г
Сч.факт.№774от 29 июня 2020г
Сч.факт.№ 262 от 29 мая 2020г.
Сч.фактура №АН-0008898 от20 июля 2020г
Сч.фактура №АН-0008450 от13 июля 2020г
Сч.фактура №ШД000270242/01 от 25июня 2020г
Сч.фактура №04073/20 от 28 июля 2020г
Сч.факт.№ 262 от 29 мая 2020г
Сч.фактура № 852от 19.06.2020г
Сч.Фак.№ 103 от 23 июня 2020г
Сч.факт.№ 94 от 30.06.2020г
Сч.факт.№637 от16.07.2020
Сч.факт.№ 451 от 22.07.2020
Сч.факт.№466 от 12.08.2020г
Сч.факт.№451 от 22.07.2020г
Сч.факт.№209 от 31.07.2020г.2020г
Сч.факт.№ 057/17508 от 03.08.2020г
Сч.факт.№ 057/17240 от 06.07.2020г
Сч.факт.№ 057/17241от 06.07.2020г
Сч.факт.№ 057/14934от 13.07.2020г
Сч.факт.№ 057/15751от 19.07.2020г
Сч.факт.№ 057/19414от 21.07.2020г
Сч.факт.№ 8894от 27.07.2020г
Сч.факт.№ 057/10750от 27.05.2020г
Сч.факт. №1416 от 09.июля 2020г
Сч.факт. №1416 от 09.июля 2020гайс-лист
Сч. факт № 437 от 23 мая 2020г.№481 от 06 июня 2020г.№575 от 02 июня 2010г
Сч.фак.№УТ2578 от 27.04.2020
Сч.фак.№УТ4421 от 29.06.2020
Сч.фак.№УТ6051 от 12.08.2020
Сч.фак.№021-00198679/3316 от 05.08. 2020г
Сч.фак.№ УТ5545 от 30.07. 2020г
Сч.фак.№021-010198679/3316 от 05.08. 2020г
Сч.факт № 20390 от 05.08.2020г
Сч.факт. №6038 от 01 июня 2020г
Сч. факт. № 83 от 03.08.2020
Сч. факт. № 89 от 06.08.2020
Сч. факт. № 80 от 30.07.2020
Сч. факт. №98 от 24.08.2020
Сч. факт. №96 от 24.08.2020
Сч. факт. №80 от 30.07.2020
Сч. факт. №83от 03.08.2020
Сч. факт. №89от 06.08.2020
Сч. факт. №82от 03.08.2020
Сч. факт. №96от 24.08.2020
Сч. факт. №92от 17.08.2020
Сч.факт.№5312 от 17 июля 2020г.
Сч. факт. №4910от 01.06.2020
Сч.фактура № 850от 19.06.2020ги Сч.факт. № 1140 от 05.08.2020
Сч.факт.№ ШД000270242/01 от 25 июня 2020г.
Сч.факт.№ Л117963 от 17.07.2020г.2020г
Сч.факт.№ 057/15750 от 19.07.2020г
Сч.факт.№ Л1179664от 17.07.2020г
Сч.факт.№ 057/14933от 13.07.2020г
Сч.фак.№1140от 05.08.2020г.и №850от19.06.2020г
Сч.фак.№1140от 05.08.2020г.и №850 от19.06.2020г
Сч.фак. №1140от 05.08.2020г.и  №850 от19.06.2020г
Сч.фактура № 103от 23 июня.2020г
Сч.фактура № 774 от 29 июня.2020г
Сч.фактура №153 от 10.08.2020г
Сч.фактура №810от 05.08.2020г
Сч.фактура № 641от 20.07.2020г
Сч.фак.№33 от 7сентября 2020г
Сч.фак.№648от10.08.2020г
т03-21-01-020
Сч.фак.№23от20.08.2020г
Сч.фак.№52от 05.08.2020
Сч.фак.№ 50820004 от 05.08.2020
Сч.фак.№ 17/30-07от 30.07.2020г.
Сч.фак.№19652от 16.07.2020г.
Сч.фак.№ДП-55167от 03.09.2020г.
Сч.фак.№ДП-55167 от 03.09.2020г.
Сч.фак.№СчфЛ-0000013728от 11.09.2020г.
Сч.фак.№ 238от 14.08.2020г.
Сч.фак.№ 19652от 16.07.2020г.
Сч.фак.№ 20119от 21.07.2020г.
Сч.фак.№СфЛ143632от 19.08.2020г.
Сч.фак.№СфЛ143635от 19.08.2020г.
Сч.фак.№СфЛ117966от 17.07.2020г.
Сч.фак.№СфЛ117964от 17.07.2020г.
Сч.фак.№СфЛ128878от 31.07.2020г.
Сч.фак.№СфЛ120608от 22.07.2020г.
Сч.фак.№ 186246от 19.08.2020г.
Сч.фак.№ СфЛ143632 от 19.08.2020
Сч.фак.№ СфЛ0000013728 от 11.09.2020
Сч.фак.№ 239 от 14.08.2020
Сч.фак.№ 370 от 02.09.2020
Сч.фак.№254от 02.07.2020г.
Сч.фак.№Е-00189353/8050от 17.08.2020г.
Сч.фак.№СчфЛ-0000013730от 13.09.2020г.
Сч.фак.№829от 16.09.2020г.
Сч.факт. № 1000от 30 октября 2020г
Сч.фак.№СфЛ143631 от 18.08.2020г.
Сч.фак.№1752 от 02.09.2020
Сч.фак.№057/22089 от 11.09.2020
Сч.фак.№057/22610 от 16.09.2020
Сч.фак.№323 от 24.09.2020
Сч.факт. № 1752 от 02.09.2020
Сч.факт. № ШД 00280975/01 от 03.09.2020
Сч.факт. № 057/22089 от 11.09.2020
Сч.факт. № 25274 от 21.09.2020г
Т.н. №19 от 30.10.2020гУниф.форма № Торг-12
Сч.фак.№20-00136от30.10.2020
Сч.фак.№ К-9105 от 10 сентября 2020
УПД № 273 от 30.09.2020
УПД №85 от 05.08.2020
УПД № 5686 от 13.08.2020, № УТ-1635 от 29.07.2020
УПД № УТ-1635 от 29.07.2020
УПД № 10416039 от 10.08.2020
УПД № 5170 от 27.07.2020, №5686 от 13.08.2020
УПД № 10209133 от 27.07.2020
СФ №Е-00189360/8050 от 25.08.2020
УПД № 1144 от 04.08.2020
УПД № 1356 от 27.07.2020
УПД № 85,86 от 05.08.2020
СФ № УП-191 от 01.09.2020
Торг-12 № 3275 от 16.07.2020
УПД № 19798 от 19.08.2020
УПД № 244802 от 19.08.2020
УПД № 95 от 29.07.2020
Торг-12 № РнП0001113 от 02.09.2020
УПД № 06636 от 03.09.2020
СФ № 0828-0000003 от 28.08.2020
Торг-12 № 23265 от 02.09.2020
УПД № 97 от 24.08.2020
УПД № 223 от 09.09.2020
Торг-12 №112 от 28.07.2020
УПД № 1938 от 22.07.2020
УПД № 8057 от 18.08.2020
УПД № 004/2020-0037571 от 28.07.2020
УПД № СО000130208 от 12.08.2020
СФ № 464 от 04.08.2020
Торг-12 № 1979 от 02.09.2020
УПД № дпВК0013468от 07.09.2020
Сч.фак.№ 275 от08.09.2020г
Сч.фак.№ 814-019от14.08..2020г
Сч.фак.№1142от 02.10..2020г
Сч.фак.№1258от 23.10..2020г
УПД № 10567944 от 19.08.2020
СФ № 1014-0000003 от 14.10.2020
СФ № 1016-0000002 от 16.10.2020
УПД № IPSI20-0082934/344 от 17.08.2020
УПД № СИ00178471 от 21.08.2020
УПД № 10566563 от 19.08.2020
УПД № 13678 от 24.08.2020
Торг-12 №142 от 02.09.2020
УПД № 5686 от 13.08.2020
Торг-12 № РнП0001112 от 02.09.2020
Торг-12 № РнП0001113,РнП0001112 от 02.09.2020
СФ №2089 от 30.09.2020
СФ № 2153 от 06.10.2020
СФ № 65 от 20.10.2020
СФ № 1793 от 27.08.2020
СФ № 1793 от 27.08.2020, № 1955 от 15.09.2020
СФ № 1793 от 27.08.202
СФ № 2088 от 30.09.2020
СФ № 1955 от 15.09.2020
СФ № 66 от 20.10.2020
СФ № 1793 от 27.08.2020, № 2088 от 30.09.2020
СФ №2088 от 30.09.2020
Сч.фак. №23372 от 07.09.2020г
Сч.фак.№166 от 22.07.2020
Сч.фак..№18125 от 16.07.2020
Сч.фак..№18125от 16.07.2020
Сч.фак..№21-00198680/3316от5 августа 2020г
Сч.фак..№ТС0000002142 от27 августа 2020г
Сч.фак.№152от03.09.2020
Сч.фак. № 537 от 28 сентября 2020г
Сч.фак..№23745 от18.08. 2020г
Сч.фак..№Л128879 от31июля 2020г
Сч.фак..№354 от24июля 2020г
Сч.фак..№Л143633от19 августа. 2020г
Сч.фак. №СфЛ143700 от21 августа 2020г
Сч.фак.№6719 от 17 сентября 2020г
Сч.фак. № ШД000285353/01 от 30 сентября 2020г
Сч.фак. № ШД000285353/01 от 30 сентября 2020г.Сч.фак. № ШД000285355/01 от 30 сентября 2020г
Сч.факт.№177 от 25 июля 2020г.
Сч.факт.№УТД000026842 от 19 августа 2020г.
Cч.фак. № НЖ2-012243/ 8088 от 24.12.2020
Cч.фак.№ 80 от 24.12.2020
Тн 69 от 26.03.20
ТН 107 от 29.05.20
ТН 203 от 24.08.20
договорная
Сч/ф. № 253-001 от 09.09.2020

In [90]:
# Сохраняем DataFrame df_filtered_final в Excel-файл
df_filtered_final.to_excel("filtered_data.xlsx", index=False)